<?php
/**
 * Locates the non-public application directory and boots it.
 *
 * The path is DISCOVERED at runtime rather than injected at deploy time. Each
 * candidate below is a real layout this file can find itself in; the first one
 * that actually contains src/bootstrap.php wins. Nothing is hardcoded, so the
 * app survives being moved, re-hosted, or renamed without a redeploy.
 *
 *   <account root>/public_html/api/  ->  <account root>        (deployed)
 *   backend/public/                  ->  backend/              (local repo)
 *
 * _app_root.php is an optional escape hatch for a layout none of these match.
 * It is not generated by CI and does not normally exist.
 *
 * This file and _app_root.php are both blocked by .htaccess.
 */
declare(strict_types=1);

$candidates = [];

// 1. Explicit override, if someone has deliberately placed one.
if (is_file(__DIR__ . '/_app_root.php')) {
    $override = trim((string) require __DIR__ . '/_app_root.php');
    // '/' and '' are the classic bad-injection values — never trust them.
    if ($override !== '' && $override !== '/') {
        $candidates[] = $override;
    }
}

// 2. Deployed layout: this file is in <root>/public_html/api/.
$candidates[] = dirname(__DIR__, 2);

// 3. Local repo layout: this file is in backend/public/.
$candidates[] = dirname(__DIR__);

// 4. One level deeper, for hosts that add an extra domain folder.
$candidates[] = dirname(__DIR__, 3);

$bootstrap = null;
foreach ($candidates as $candidate) {
    $file = rtrim($candidate, '/') . '/src/bootstrap.php';
    if (is_file($file)) {
        $bootstrap = $file;
        break;
    }
}

if ($bootstrap === null) {
    http_response_code(500);
    header('Content-Type: application/json');
    // The response stays generic: the candidate list would disclose the
    // server's directory layout. The detail goes to the error log only.
    echo json_encode(['error' => 'Application is not configured correctly.']);
    error_log('Diwan: src/bootstrap.php not found. Tried: ' . implode(', ', $candidates));
    exit(1);
}

require $bootstrap;
